---
title: ""
format: 
  html:
    toc: true
    toc-location: left
    toc-title: 'Année' 
---



## 2024

- Ameline, C., **Lafage, D.**, Vernon, P., Hedde, M., Petillon, J. 2024. Spiders 
bring new insight into the eco-evolutionary drivers of body size variation and
sexual size dimorphism in arthropods. *bioRXiv*. [https://doi.org/10.1101/2024.10.30.621136](https://doi.org/10.1101/2024.10.30.621136) [{{< fa file-pdf >}}](./Ameline_BioRxiv2024.pdf)  

## 2023


- Marker, J., Bergman, E., Bowes, R. **Lafage, D.** 2023. Small stream predators rely heavily on terrestrial matter energy input in the fall, regardless of riparian buffer size. *Food Webs*. [https://doi.org/10.1016/j.fooweb.2023.e00302](https://doi.org/10.1016/j.fooweb.2023.e00302) [{{< fa file-pdf >}}](./Marker_FoodWebs2023.pdf)

- Marker, J., Erlandsson, A., Bergman, E., **Lafage, D.** 2023. Riparian clear-cuts affect the source of riparian spider prey depending on capture stategy. Under review.

- Marker, J., **Lafage, D.**, Bergman, E., Erlandsson, A. 2023 Molecular gut content analysis results are determined by various biotic factors in wolf spiders (Aranae: Lycosidae). Under review.

## 2022

- Marker, J., Bergman, E., Eckstein, L., **Lafage, D.** 2022. Forested riparian buffer environmental variables are more important than size for species functional diversity in production forests. *Forest Ecology and Management*. [https://doi.org/10.1016/j.foreco.2022.120599](https://doi.org/10.1016/j.foreco.2022.120599) [{{< fa file-pdf >}}](./Marker_ForestEcol2022.pdf)

- Monsimet, J., Pétillon, J. Devineau, O., Gardoni, N., Bataillard, L., **Lafage, D.** 2022. Contrasted propensity for waterborne and airborne dispersal between two closely related semi‐aquatic spider species. *Insect Conservation and Diversity*. [https://doi.org/10.1111/icad.12596](https://doi.org/10.1111/icad.12596) [{{< fa file-pdf >}}](./Monsimet_InsectConservation2022.pdf)

- Dickel, L., Monsimet, J., **Lafage, D.**, Devineau, O. 2022. Characterization of habitat requirements of European fishing spiders. *PeerJ*. [https://doi.org/10.7717/peerj.12806](https://doi.org/10.7717/peerj.12806) [{{< fa file-pdf >}}](./Dickel_PeerJ2022.pdf)

- Marker, J., **Lafage, D.**, Bergman, E., Bowes, R.E. 2022. Greater than the sum of your parts: Nonlethal stable isotope sampling methods in spiders. *Ecosphere*. [https://doi.org/10.1002/ecs2.3903](https://doi.org/10.1002/ecs2.3903) [{{< fa file-pdf >}}](./Marker_Ecosphere2022.pdf)


## 2021

- Mammola, S., Pétillon, J., Hacala, A., Monsimet, J., Marti, S-L., Cardoso, P., **Lafage. D.** 2021. Challenges and opportunities of species distribution modelling of terrestrial arthropod predators. *Diversity and distributions*. [https://doi.org/10.1111/ddi.13434](https://doi.org/10.1111/ddi.13434) [{{< fa file-pdf >}}](./Mammola_DiversityDistribution2021.pdf)

- Pekár, S. et al. 2021. The World Spider Trait database: a centralized global open repository for curated data on spider traits. *Database*. [https://doi.org/10.1093/database/baab064](https://doi.org/10.1093/database/baab064) [{{< fa file-pdf >}}](./Pekar_Database2021.pdf)

- Hacala, A., **Lafage, D.**, Prinzing, A., Sawtschuk, J., Pétillon, J. 2021. Drivers of taxonomic, functional and phylogenetic diversities in dominant ground-dwelling arthropods of coastal heathlands. *Oecologia*. [https://doi.org/10.1007/s00442-021-05032-4](https://doi.org/10.1007/s00442-021-05032-4) [{{< fa file-pdf >}}](./Hacala_Oecologia2021.pdf)

- Ridel, A., **Lafage, D.**, Devogel, P., Lacoue-Labarthe, T., Petillon, J. 2021. Habitat filtering differentially modulates phylogenetic and functional diversity relationships between predatory arthropods. *Royal Society open science*. [https://doi.org/10.1098/rsos.202093](https://doi.org/10.1098/rsos.202093) [{{< fa file-pdf >}}](./Ridel_RSOS2021.pdf)

- Monsimet, J., Colinet, H., Devineau, O., **Lafage, D.**, Pétillon, J. 2021. Biogeographic position and body size jointly set lower thermal limits of wandering spiders. *Ecology and evolution*. [https://doi.org/10.1002/ece3.7286](https://doi.org/10.1002/ece3.7286) [{{< fa file-pdf >}}](./Monsimet_EcologyEvolution2021.pdf)

- Monsimet, J. Colinet, H., **Lafage, D.**, Devineau, O., Pétillon, J. 2021. Replication Data for: Biogeographic position and body size jointly set lower thermal limits of wandering spiders. *DataverseNO*.

- **Lafage, D.**, Carpentier, A., Duhamel, S., Dupuy, C., Feunteun, E., Lesourd, S., Pétillon, J. 2021. Site characteristics more than vegetation type influence food web structure of intertidal salt marshes. *Frontiers in Marine Science*. [https://doi.org/10.3389/fmars.2021.669759](https://doi.org/10.3389/fmars.2021.669759) [{{< fa file-pdf >}}](./Lafage_FrontiersMarine2021.pdf)


## 2020


- Monsimet, J., Devineau, O., Petillon, J., **Lafage, D.** 2020. Explicit integration of dispersal-related metrics improves predictions of SDM in predatory arthropods. *Scientific Reports*.[https://doi.org/10.1038/s41598-020-73262-2](https://doi.org/10.1038/s41598-020-73262-2) [{{< fa file-pdf >}}](./Monsimet_ScientificReports2020.pdf)

- **Lafage, D.**, Elbrecht, V., Cuff, J.P., Steinke, D., Hambäck, P.A., Erlandsson, A. 2020. A new primer for metabarcoding of spider gut contents. *Environmenral DNA*. [https://doi.org/10.1002/edn3.62](https://doi.org/10.1002/edn3.62)  [{{< fa file-pdf >}}](./Lafage_EDNA2020.pdf)

## 2019

- **Lafage, D.**, Djoudi, E.A., Perrin, G., Gallet, S., Pétillon, J. 2019. Responses of ground-dwelling spider assemblages to changes in vegetation from wet oligotrophic habitats of Western France. *Arthropod-Plant Interactions*. [https://doi.org/10.1007/s11829-019-09685-0](https://doi.org/10.1007/s11829-019-09685-0) [{{< fa file-pdf >}}](./Lafage_API2020.pdf)

- **Lafage, D.**, Bergman, E., Eckstein, R.L., Österling, E.M., Sadler, J.P., Piccolo, J.J. 2019. Local and landscape drivers of aquatic‐to‐terrestrial subsidies in riparian ecosystems: A worldwide meta‐analysis. *Ecosphere*. [https://doi.org/10.1002/ecs2.2697](https://doi.org/10.1002/ecs2.2697) [{{< fa file-pdf >}}](./Lafage_Ecosphere2019.pdf)

## 2018

- Pétillon, J., François, A., **Lafage, D.** 2018. Short–term effects of horse grazing on spider assemblages of a dry meadow (Western France). *Animal Biodiversity and Conservation*. [https://doi.org/10.32800/abc.2018.41.0019](https://doi.org/10.32800/abc.2018.41.0019) [{{< fa file-pdf >}}](./Petillon_ABC2018.pdf)

## 2016

- **Lafage D.** & Pétillon, J. 2016. Relative importance of management and natural flooding on spider, carabid and plant assemblages in extensively used grasslands along the Loire. *Basic and Applied Ecology*. [https://doi.org/10.1016/j.baae.2016.04.002](https://doi.org/10.1016/j.baae.2016.04.002) [{{< fa file-pdf >}}](./Lafage_BAE2016.pdf)

## 2015

- **Lafage, D.**, Sibelle, C., Secondi, J., Canard, A., Pétillon, J. 2015. Short‐term resilience of arthropod assemblages after spring flood, with focus on spiders (Arachnida: Araneae) and carabids (Coleoptera: Carabidae). *Ecohydrology*. [https://doi.org/10.1002/eco.1606](https://doi.org/10.1002/eco.1606) [{{< fa file-pdf >}}](./Lafage_Ecohydrology2015.pdf)

- **Lafage, D.**, Maugenest, S., Bouzillé, J-B., Pétillon, J. 2015. Disentangling the influence of local and landscape factors on alpha and beta diversities: opposite response of plants and ground-dwelling arthropods in wet meadows. *Ecological Research*. [https://doi.org/10.1007/s11284-015-1304-0](https://doi.org/10.1007/s11284-015-1304-0)  [{{< fa file-pdf >}}](./Lafage_EcoRes2015.pdf)

## 2014

- **Lafage D.** & Pétillon, J. 2014. Impact of cutting date on carabids and spiders in a wet meadow. *Agriculture, ecosystems & environment*. [https://doi.org/10.1016/j.agee.2013.11.027](https://doi.org/10.1016/j.agee.2013.11.027) [{{< fa file-pdf >}}](./Lafage_AEE2014.pdf)

## 2013

- **Lafage, D.**, Secondi, J., Georges, A., Bouzillé, J-B., Pétillon, J. 2014. Satellite‐derived vegetation indices as surrogate of species richness and abundance of ground beetles in temperate floodplains. *Insect Conservation and Diversity*. [https://doi.org/10.1111/icad.12056](https://doi.org/10.1111/icad.12056)  [{{< fa file-pdf >}}](./Lafage_ICD2013.pdf)

- Varet, M., Burel, F., **Lafage, D.**, Pétillon, J. 2013. Age-dependent colonization of urban habitats: a diachronic approach using carabid beetles and spiders. *Animal Biology*. [https://doi.org/10.1163/15707563-00002410](https://doi.org/10.1163/15707563-00002410)  [{{< fa file-pdf >}}](./Varet_Animal_Biology2013.pdf)

## 2004

- Laffaille, P., Briand, C., Fatin, D., **Lafage, D.**, Lasne, E. Point sampling the abundance of European eel (Anguilla anguilla) in freshwater areas. *Archiv fur Hydrobiologie*. [https://doi.org/10.1127/0003-9136/2005/0162-0091](https://doi.org/10.1127/0003-9136/2005/0162-0091)  [{{< fa file-pdf >}}](./Laffaille_AFH2004.pdf) 